### ISSUE TITLE
Should scoring be based on active challenges only?

### ISSUE THREAD

**Issue by Corb3nik** [OpenToAllCTF/OTA-University#2]
At some point, we might have to disable certain challenges because they are old or broken.

In the event that we disable them, should users' scores be updated accordingly?

Example : 
1. User X solves challenge Y for 500 points
2. We remove challenge Y

Should user X have 0 points or 500 points?

**Comment by reznok** [comment]
The question is: Do we want to keep veterans at the top of the scoreboard, or encourage ongoing competition for the top scoreboard slots?

New players will permanently be at a disadvantage if X keeps the 500 points. This platform is for teaching and learning, but competition fuels a lot of people (myself included!).

However, there's also potentially value in recognizing veterans that have been around since the beginning. Perhaps this could be accomplished in another way via titles/badges though?

**Comment by Kileak** [comment]
Second that challenges shouldn't be taken into calculation, if they cannot be solved anymore.

**Comment by Corb3nik** [comment]
Yep :) Closing this issue. Challenges will _not_ be taken offline unless they are broken. In the event where a challenge isn't fixable for some reason, the challenge will be taken down and scoring will be updated accordingly.
